### ISSUE TITLE
api建议

### ISSUE THREAD

**Issue by Mayandev** [kapeter/mpMasonry#2]
建议增加一个点击事件的api，这样就更完善了，望采纳！

**Comment by kapeter** [comment]
点击事件可以直接加在元素item，即例子中的img-box，处于这个考虑没在组件中添加点击事件。

**Comment by kapeter** [comment]
> 建议增加一个点击事件的api，这样就更完善了，望采纳！

点击事件可以直接加在元素item，即例子中的img-box，处于这个考虑没在组件中添加点击事件。

**Comment by zhufengyi01** [comment]
组建点击事件和生命周期不响应
